In [ ]:
import numpy as np

In [ ]:
## Convolution function
def Convolution(image, filter, stride=1, padding=0):
    """
    Question (a)
    Implement your own conv function which performs convolution operation without using any neural network packages.
    Make sure to handle all possible edge cases to receive full credits as your implementation will be tested with 20 test cases (1 pt for each test case).
    Keep in mind that height and width of the given image or filter are not always the same.

    Inputs
    - image: 2D numpy array 
    - filter: 2D numpy array
    - stride, padding: integers

    Outputs:
    - 2D numpy array : convolution results of the given image and filter..
    - Return None if stride is not compatible. (ex. image of 5*5 with filter 2*2 with stride 2, padding 0)
    - Return None if filter is larger than the given image.
    """

    ### COMPLETE HERE ###
    IMAGE = image
    FILTER = filter
    IMAGE_TRF = np.pad(IMAGE, (padding,padding), 'constant', constant_values = 0)
    
    # height에 대한 고려
    if (IMAGE.shape[0] - FILTER.shape[0] + 2*padding) % stride != 0:
        return None
    elif (IMAGE.shape[0] - FILTER.shape[0] + 2*padding) < 0:
        return None

    # width에 대한 고려
    if (IMAGE.shape[1] - FILTER.shape[1] + 2*padding) % stride != 0:
        return None
    elif (IMAGE.shape[1] - FILTER.shape[1] + 2*padding) < 0:
        return None
    
    
    FEATUREMAP_height = (IMAGE.shape[0] - FILTER.shape[0] + 2*padding)/stride + 1
    FEATUREMAP_width = (IMAGE.shape[1] - FILTER.shape[1] + 2*padding)/stride + 1
    
    FEATUREMAP_height = int(FEATUREMAP_height)
    FEATUREMAP_width = int(FEATUREMAP_width)

    FEATUREMAP = []
    for i in range(IMAGE_TRF.shape[0] - (FILTER.shape[0]-1)):
        FEATUREMAP_row = []
        if (i % stride == 0):
            for j in range(IMAGE_TRF.shape[1] - (FILTER.shape[1]-1)):
                if (j % stride == 0):
                    COMPARED = np.zeros((FILTER.shape[0], FILTER.shape[1]))
                    for l in range(COMPARED.shape[0]):
                        for k in range(COMPARED.shape[1]):
                            COMPARED[l][k] = IMAGE_TRF[i+l][j+k]
                    ELEMENT = np.sum(COMPARED*FILTER)
                    FEATUREMAP_row.append(ELEMENT)
            FEATUREMAP.append(FEATUREMAP_row)
    FEATUREMAP = np.array(FEATUREMAP)

    output = FEATUREMAP
    
    ### COMPLETE HERE ###
    
    return output

In [1]:
import numpy as np

def Convolution(image, filter, stride=1, padding=0):
    """
    Question (a)
    Implement your own conv function which performs convolution operation without using any neural network packages.
    Make sure to handle all possible edge cases to receive full credits as your implementation will be tested with 20 test cases (1 pt for each test case).
    Keep in mind that height and width of the given image or filter are not always the same.

    Inputs
    - image: 2D numpy array 
    - filter: 2D numpy array
    - stride, padding: integers

    Outputs:
    - 2D numpy array : convolution results of the given image and filter..
    - Return None if stride is not compatible. (ex. image of 5*5 with filter 2*2 with stride 2, padding 0)
    - Return None if filter is larger than the given image.
    """

    ### COMPLETE HERE ###

    # determine the resulting data size, while handling boundary cases
    # print(image.shape)
    if image.ndim != 2 or filter.ndim != 2:
        # print('the dimension of either image or filter is not 2.')
        return None
    if stride <= 0:
        # print('the size of stride should be positive. 0 is also not allowed.')
        return None
    if padding < 0:
        # print('the size of padding should be non-negative.')
        return None
    dividend = (image.shape[1] - filter.shape[1] + 2 * padding)
    if dividend % stride != 0 or dividend < 0:
        # print('the size of stride is not compatible.(not divisible, too large filter, etc.')
        return None
    w_prime =  dividend / stride + 1
    dividend = (image.shape[0] - filter.shape[0] + 2 * padding)
    if dividend % stride != 0 or dividend < 0:
        # print('the size of stride is not compatible.(not divisible, too large filter, etc.')
        return None
    h_prime = dividend / stride + 1
    w_prime, h_prime = int(w_prime), int(h_prime)
    
    # put padding
    image_copied = image.copy()
    zeros_vert = np.zeros(shape=[image_copied.shape[0], padding])
    image_copied = np.concatenate([zeros_vert, image_copied, zeros_vert], axis=1)
    zeros_hori = np.zeros(shape=[padding, image_copied.shape[1]])
    image_copied = np.concatenate([zeros_hori, image_copied, zeros_hori], axis=0)

    # print(image_copied)
    
    # convolve over the image
    acc = []
    # print(filter.shape)
    for h in range(h_prime):
        for w in range(w_prime):
            # patch = image_copied[h * stride:h * stride + filter.shape[1], w * stride:w * stride + filter.shape[0]]
            patch = image_copied[h * stride:h * stride + filter.shape[0], w * stride:w * stride + filter.shape[1]]
            acc.append((patch * filter).sum())

    output = np.array(acc).reshape(h_prime, w_prime)
    
    ### COMPLETE HERE ###
    
    return output

In [2]:
image = np.array([[1, 2, 3, 2, 1], 
                  [2, 3, 4, 5, 6], 
                  [-1, -2, -3, -4, -5], 
                  [0, 0, 1, 0, 0], 
                  [7, 1, 7, 1, 7]])

filter = np.array([[1, 0], 
                   [0, 1]])

print(Convolution(image, filter, stride=3, padding=0))

"""
Answer:
array([[4., 8.],
       [1., 7.]])
"""

[[4. 8.]
 [1. 7.]]


'\nAnswer:\narray([[4., 8.],\n       [1., 7.]])\n'

In [3]:
image = np.array(
    [[0, 1, 7, 5],
     [5, 5, 6, 6], 
     [5, 3, 3, 0],
     [1, 1, 1, 2]]
)

filter = np.array(
    [[1, 0], 
     [1, 2]]
)

print(Convolution(image, filter, stride=2, padding=0))

"""
Answer:
array([[15., 25.],
       [ 8.,  8.]])
"""

[[15. 25.]
 [ 8.  8.]]


'\nAnswer:\narray([[15., 25.],\n       [ 8.,  8.]])\n'

In [4]:
image = np.array(
    [[0, 1, 7, 5],
     [5, 5, 6, 6], 
     [5, 3, 3, 0],
     [1, 1, 1, 2]]
)

filter = np.array(
    [[1, 0, 0], 
     [1, 2, 1], 
     [1, 2, 3]]
)

print(Convolution(image, filter, stride=1, padding=0))

"""
Answer:
array([[41., 33.],
       [25., 23.]])
"""

[[41. 33.]
 [25. 23.]]


'\nAnswer:\narray([[41., 33.],\n       [25., 23.]])\n'

In [5]:
image = np.array(
    [[0, 1, 7, 5],
     [5, 5, 6, 6], 
     [5, 3, 3, 0],
     [1, 1, 1, 2]]
)

filter = np.array(
    [[1, 0, 0], 
     [1, 2, 1], 
     [1, 2, 3]]
)

print(Convolution(image, filter, stride=1, padding=1))

"""
Answer:
array([[26., 42., 55., 35.],
       [34., 41., 33., 28.],
       [18., 25., 23., 14.],
       [ 3.,  9.,  8.,  8.]])
"""

[[26. 42. 55. 35.]
 [34. 41. 33. 28.]
 [18. 25. 23. 14.]
 [ 3.  9.  8.  8.]]


'\nAnswer:\narray([[26., 42., 55., 35.],\n       [34., 41., 33., 28.],\n       [18., 25., 23., 14.],\n       [ 3.,  9.,  8.,  8.]])\n'

In [6]:
image = np.array(
    [[1, 1, 1, 0, 0],
     [0, 1, 1, 1, 0], 
     [0, 0, 1, 1, 1],
     [0, 0, 1, 1, 0],
     [0, 1, 1, 0, 0]]
)

filter = np.array(
    [[1, 0, 1], 
     [0, 1, 0], 
     [1, 0, 1]]
)

print(Convolution(image, filter, stride=1, padding=0))

"""
Answer:
array([[4., 3., 4.],
       [2., 4., 3.],
       [2., 3., 4.]])
"""

[[4. 3. 4.]
 [2. 4. 3.]
 [2. 3. 4.]]


'\nAnswer:\narray([[4., 3., 4.],\n       [2., 4., 3.],\n       [2., 3., 4.]])\n'

In [7]:
image = np.array(
    [[1, 2, 3, 0],
     [0, 1, 2, 3], 
     [3, 0, 1, 2],
     [2, 3, 0, 1]]
)

filter = np.array(
    [[2, 0, 1], 
     [0, 1, 2], 
     [1, 0, 2]]
)

print(Convolution(image, filter, stride=1, padding=0))

"""
Answer:
array([[15., 16.],
       [ 6., 15.]])
"""

[[15. 16.]
 [ 6. 15.]]


'\nAnswer:\narray([[15., 16.],\n       [ 6., 15.]])\n'

In [8]:
image = np.array(
    [[1, 2, 3, 0],
     [0, 1, 2, 3], 
     [3, 0, 1, 2],
     [2, 3, 0, 1]]
)

filter = np.array(
    [[2, 0, 1], 
     [0, 1, 2], 
     [1, 0, 2]]
)

print(Convolution(image, filter, stride=1, padding=1))

"""
Answer:
array([[ 7., 12., 10.,  2.],
       [ 4., 15., 16., 10.],
       [10.,  6., 15.,  6.],
       [ 8., 10.,  4.,  3.]])
"""

[[ 7. 12. 10.  2.]
 [ 4. 15. 16. 10.]
 [10.  6. 15.  6.]
 [ 8. 10.  4.  3.]]


'\nAnswer:\narray([[ 7., 12., 10.,  2.],\n       [ 4., 15., 16., 10.],\n       [10.,  6., 15.,  6.],\n       [ 8., 10.,  4.,  3.]])\n'

In [9]:
image = np.array(
    [[1, 2, 3, 0, 1, 2, 3],
     [0, 1, 2, 3, 0, 1, 2], 
     [3, 0, 1, 2, 3, 0, 1],
     [2, 3, 0, 1, 2, 3, 0],
     [1, 2, 3, 0, 1, 2, 3],
     [0, 1, 2, 3, 0, 1, 2],
     [3, 0, 1, 2, 3, 0, 1]]
)

filter = np.array(
    [[2, 0, 1], 
     [0, 1, 2], 
     [1, 0, 2]]
)

print(Convolution(image, filter, stride=2, padding=0))

"""
Answer:
array([[15., 17., 15.],
       [17., 15., 17.],
       [15., 17., 15.]])
"""

[[15. 17. 15.]
 [17. 15. 17.]
 [15. 17. 15.]]


'\nAnswer:\narray([[15., 17., 15.],\n       [17., 15., 17.],\n       [15., 17., 15.]])\n'

In [10]:
image = np.array(
    [[0, 3, 2, 1],
     [2, 1, 0, 2], 
     [1, 3, 2, 0],
     [2, 0, 3, 3]]
)

filter = np.array(
    [[1, 0, 1], 
     [0, 1, 0], 
     [1, 0, 1]]
)

print(Convolution(image, filter, stride=2, padding=2))

"""
Answer: None
"""

None


'\nAnswer: None\n'

In [ ]:
image = np.array(
    [[0, 3, 2, 1],
     [2, 1, 0, 2], 
     [1, 3, 2, 0],
     [2, 0, 3, 3],
     [1, 0, 1, 2]]
)

filter = np.array(
    [[1, 0], 
     [3, 1]]
)

print(Convolution(image, filter, stride=1, padding=0))

"""
Answer:
array([[ 7.,  6.,  4.],
       [ 8., 12.,  6.],
       [ 7.,  6., 14.],
       [ 5.,  1.,  8.]])
"""

[[ 7.  6.  4.]
 [ 8. 12.  6.]
 [ 7.  6. 14.]
 [ 5.  1.  8.]]


'\nAnswer:\narray([[ 7.,  6.,  4.],\n       [ 8., 12.,  6.],\n       [ 7.,  6., 14.],\n       [ 5.,  1.,  8.]])\n'

In [ ]:
image = np.array(
    [[0, 1, 2, 0],
     [3, 0, 2, 1], 
     [1, 0, 3, 2],
     [2, 1, 1, 0]]
)

filter = np.array(
    [[1, 0, 0], 
     [0, 1, 0], 
     [0, 0, 1]]
)

print(Convolution(image, filter, stride=1, padding=1))

"""
Answer:
array([[0., 3., 3., 0.],
       [3., 3., 5., 3.],
       [2., 4., 3., 4.],
       [2., 2., 1., 3.]])
"""

[[0. 3. 3. 0.]
 [3. 3. 5. 3.]
 [2. 4. 3. 4.]
 [2. 2. 1. 3.]]


'\nAnswer:\narray([[0., 3., 3., 0.],\n       [3., 3., 5., 3.],\n       [2., 4., 3., 4.],\n       [2., 2., 1., 3.]])\n'