In [1]:
import numpy as np

In [2]:
B = np.array([[0, 1, -1],
             [-1, -3, -3], 
             [2, 1, 5],
             [0, -1, 0],
             [2, 2, 7]], dtype=np.float64)
print(B)
print(B.shape)

[[ 0.  1. -1.]
 [-1. -3. -3.]
 [ 2.  1.  5.]
 [ 0. -1.  0.]
 [ 2.  2.  7.]]
(5, 3)


In [3]:
X = np.array([[-1, -9, -1, 4, 1]], dtype=np.float64).T
print(X)
print(X.shape)

[[-1.]
 [-9.]
 [-1.]
 [ 4.]
 [ 1.]]
(5, 1)


In [4]:
print(B.T)
print(np.transpose(B))
print(B.T == np.transpose(B))

[[ 0. -1.  2.  0.  2.]
 [ 1. -3.  1. -1.  2.]
 [-1. -3.  5.  0.  7.]]
[[ 0. -1.  2.  0.  2.]
 [ 1. -3.  1. -1.  2.]
 [-1. -3.  5.  0.  7.]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [5]:
left = B.T.dot(B)
print(left)
print(left.shape)

[[ 9.  9. 27.]
 [ 9. 16. 27.]
 [27. 27. 84.]]
(3, 3)


In [6]:
## obtain the determinant and inverse
print(np.linalg.det(left))

189.00000000000003


In [7]:
## since the determinant is nonzero, there exists inverse
left_inv = np.linalg.inv(left)
print(left_inv)
print(left_inv.shape)

[[ 3.25396825 -0.14285714 -1.        ]
 [-0.14285714  0.14285714  0.        ]
 [-1.         -0.          0.33333333]]
(3, 3)


In [8]:
## now obtain the lambda vector
mat_part = left_inv.dot(B.T)
lbda = mat_part.dot(X)
print(lbda)
print(lbda.shape)

[[-4.]
 [ 2.]
 [ 1.]]
(3, 1)


In [9]:
pi = np.zeros(shape=(5, ))
for i in range(len(lbda)):
    print(f"lambda:{lbda[i][0]}, vector:{B[:, i]}")
    pi += lbda[i][0] * B[:, i]

print(pi)

lambda:-3.9999999999999982, vector:[ 0. -1.  2.  0.  2.]
lambda:1.9999999999999998, vector:[ 1. -3.  1. -1.  2.]
lambda:0.9999999999999996, vector:[-1. -3.  5.  0.  7.]
[ 1. -5. -1. -2.  3.]


In [10]:
import numpy as np

## define B and X
B = np.array([[0, 1, -1],
             [-1, -3, -3], 
             [2, 1, 5],
             [0, -1, 0],
             [2, 2, 7]], dtype=np.float64)
X = np.array([[-1, -9, -1, 4, 1]], dtype=np.float64).T

## obtain the inverse part of the projection formula
inv_part = np.linalg.inv(B.T.dot(B))
mat_part = inv_part.dot(B.T) # equivalent to (B^T*B)^(-1)*B^T
lbda = mat_part.dot(X)
print(lbda) # -4, 2, 1

## obtain the projection
pi = np.zeros(shape=(B.shape[0], ))
for i in range(len(lbda)):
    print(f"lambda:{lbda[i][0]}, vector:{B[:, i]}")
    pi += lbda[i][0] * B[:, i]

pi = pi.reshape(X.shape)
print(pi) # 1, -5, -1, -2, 3

[[-4.]
 [ 2.]
 [ 1.]]
lambda:-3.9999999999999982, vector:[ 0. -1.  2.  0.  2.]
lambda:1.9999999999999998, vector:[ 1. -3.  1. -1.  2.]
lambda:0.9999999999999996, vector:[-1. -3.  5.  0.  7.]
[[ 1.]
 [-5.]
 [-1.]
 [-2.]
 [ 3.]]


In [13]:
def l2_norm(X:np.ndarray) -> float:
    X = np.array(X, dtype=np.float64)
    self_dot = X.T.dot(X).flatten() # returns 1d array
    return self_dot[0]

diff = X - pi
print(l2_norm(diff))

60.0


In [14]:
diff = X - pi
print(diff)

[[-2.00000000e+00]
 [-4.00000000e+00]
 [-1.77635684e-15]
 [ 6.00000000e+00]
 [-2.00000000e+00]]


In [15]:
print(l2_norm(diff))

60.0
